### ISSUE TITLE
iOS SDK Crash - EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by DennisWolfeDSW** [Adobe-Marketing-Cloud/acp-sdks#184]
### Problem

We're seeing a crash in the iOS SDK that seems like it could be related to accessing a null pointer in the C++ portion of the SDK.

### Environment

Xcode Version: 10.2.1 (10E1001)
Adobe SDK Version: 
ACPCore - 2.3.2
ACPTarget - 2.1.1
ACPMobileServices - 1.0.0
Steps to reproduce: Unknown. Actively trying to reproduce. The crash seems to occur shortly after the app is launched.

### SDK Integration
We've integrated with the SDK manually instead of using cocoapods. Here is a rough code sample of how we initialize and use the SDK.

```
APCore.setLogLevel(.error)
ACPCore.configure(withAppId: ...)
ACPIdentity.registerExtension()
ACPTarget.registerExtension()
ACPMobileServices.registerExtension()
ACPCore.start()
ACPTarget.prefetchContent(..., with: nil) { _ in }
```

### Crash Log

Crashed: Configuration R
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

0  MobileApp                      0x102ed5eb0 AdobeMarketingMobile::Module::UnregisterAllRules() + 4372537008
1  MobileApp                      0x102eb3630 AdobeMarketingMobile::Configuration::OnRulesDownloaded(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4372395568
2  MobileApp                      0x102f08480 AdobeMarketingMobile::RulesDownloader::OnDownloadComplete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4372743296
3  MobileApp                      0x102f082f8 AdobeMarketingMobile::RulesDownloader::StartDownload(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4372742904
4  MobileApp                      0x102eb7c8c std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'(), std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'()>, void ()>::operator()() + 4372413580
5  MobileApp                      0x102edfadc AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4372576988
6  MobileApp                      0x102eb7810 std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10, std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10>, void ()>::operator()() + 4372412432
7  MobileApp                      0x102edfadc AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4372576988
8  MobileApp                      0x102ee1bd0 std::__1::__function::__func<AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0::operator()() const::'lambda'(), std::__1::allocator<AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0::operator()() const::'lambda'()>, void ()>::operator()() + 4372585424
9  MobileApp                      0x102edfadc AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4372576988
10 MobileApp                      0x102edfa34 AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 4372576820
11 MobileApp                      0x102ee18b0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0> >(void*) + 4372584624
12 libsystem_pthread.dylib        0x1b67582c0 _pthread_body + 128
13 libsystem_pthread.dylib        0x1b6758220 _pthread_start + 44
14 libsystem_pthread.dylib        0x1b675bcdc thread_start + 4

**Comment by shalehaha** [comment]
@DennisWolfeDSW 

Thanks for reporting the issue, we have seen similar crashes and are working on it. Will update the tickets when we have an update.

Jiabin

**Comment by rodrigomarcelino** [comment]
I'm having the same problem, in the latest release this problem have been solved?

**Comment by renanvs** [comment]
Hi@shalehaha,
Is there some way to adjust or a prediction to release a new version to fix this?

The top crashes of our app came from this error

**Comment by shalehaha** [comment]
@DennisWolfeDSW  @renanvs  @rodrigomarcelino 

This crash should have been fixed on the version 2.3.3 which we just released today. Go check it out and let us know if you have further questions. Thanks.

Jiabin

**Comment by pr096100** [comment]
Hi I am facing the same crash, kindly help on the same
below are the packages used as part of project through cocaapods
    pod 'ACPTarget'#, '
    pod 'ACPMobileServices'
    pod 'ACPAnalytics'#
    pod 'ACPAudience'
    pod 'ACPCore'
    pod 'ACPUserProfile'

**Comment by GeorgiDamyanov** [comment]
We still get crash reports with the same issue on SKD version:

ACPCore  2.3.5
ACPIdentity 2.1.3
ACPLifecycle 2.0.3
ACPSignal 2.0.2

The setup calls we make:

```
ACPCampaign.registerExtension()
ACPAudience.registerExtension()
ACPAnalytics.registerExtension()
ACPUserProfile.registerExtension()
ACPIdentity.registerExtension()
ACPLifecycle.registerExtension()
ACPSignal.registerExtension()
ACPPlaces.registerExtension()

// Start Core configuation
ACPCore.start {
   ACPCore.configure( withAppId: adobeAppId )
}

// Start the life cyclea with the current system information
ACPCore.lifecycleStart( _systemInfo )

// Track pushNotifications
ACPCore.setPushIdentifier( pushIdentifier )
```

Crash report

```
#24. Crashed: Configuration R
0  MobileApp                       0x106088c18 AdobeMarketingMobile::Module::UnregisterAllRules() + 20
1  MobileApp                       0x106062d8c AdobeMarketingMobile::Configuration::OnRulesDownloaded(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 204
2  MobileApp                       0x1060bb928 AdobeMarketingMobile::RulesDownloader::OnDownloadComplete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 156
3  MobileApp                       0x1060bb5b0 AdobeMarketingMobile::RulesDownloader::StartDownload(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 436
4  MobileApp                       0x106067814 std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'(), std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'()>, void ()>::operator()() + 140
5  MobileApp                       0x10609331c AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 28
6  MobileApp                       0x106067380 std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10, std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10>, void ()>::operator()() + 188
7  MobileApp                       0x10609331c AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 28
8  MobileApp                       0x106095b9c std::__1::__function::__func<AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0::operator()() const::'lambda'(), std::__1::allocator<AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0::operator()() const::'lambda'()>, void ()>::operator()() + 644
9  MobileApp                       0x10609331c AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 28
10 MobileApp                       0x106093274 AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 64
11 MobileApp                       0x1060957f0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_0> >(void*) + 96
12 libsystem_pthread.dylib        0x1b13bdd8c _pthread_start + 156
13 libsystem_pthread.dylib        0x1b13c176c thread_start + 8
```

**Comment by pr096100** [comment]
Ok, Thanks for the updates

**Comment by shalehaha** [comment]
@pr096100 @GeorgiDamyanov 

Can you please double-check whether the crashes were happening on your latest app (with updated SDK) or they were from old versions?

If you have confirmed this is still an issue, please reach out to the [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket, we need more information and it'd good if there is any way you can reproduce it on a dev app. 

Thanks,
Jiabin Geng

**Comment by pr096100** [comment]
Hi shalehaha ,
The issue is not observed in our latest version and thanks for resolving the issue and keep us updated.

Regards,
Prithivi
